{% set version = "1.1.0" %}

package:
  name: nda
  version: {{ version }}

source:
  url: https://github.com/TRIQS/nda/releases/download/{{ version }}/nda-{{ version }}.tar.gz
  sha256: PUT HERE THE SHA256 OF YOUR RELEASE TARBALL

build:
  number: 0
  skip: True  # [win or py<30]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - hdf5
    - {{ mpi }}
    - libblas
    - liblapack
    - python
  run:
    - hdf5
    - {{ mpi }}
    - libblas
    - liblapack
    - python

about:
  home: https://triqs.github.io/nda
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'A multi-dimensional array class for C++.'

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
